console.log("=========================================");
console.log("STARTING ALL DATAFRAME OPERATION TESTS...");
console.log("=========================================");

import "./clone.test";
import "./columns.test";
import "./cast.test";
import "./concat.test";
import "./drop.test";
import "./dropNulls.test";
import "./dtypes.test";
import "./equals.test";
import "../exceptions.test";
import "./explode.test";
import "./fillNull.test";
import "./filter.test";
import "./groupBy.test";
import "./groupByDynamic.test";
import "./grouped/agg.test";
import "./grouped/toDataframe.test";
import "./head.test";
import "./height.test";
import "./insertColumn.test";
import "./item.test";
import "./iterColumns.test";
import "./iterRows.test";
import "./join.test";
import "./joinAsof.test";
import "./joinWhere.test";
import "./limit.test";
import "./partitionBy.test";
import "./pivot.test";
import "./rename.test";
import "./reverse.test";
import "./schema.test";
import "./select.test";
import "./shape.test";
import "./slice.test";
import "./sort.test";
import "./tail.test";
import "./toArray.test";
import "./toDict.test";
import "./toDicts.test";
import "./transpose.test";
import "./unique.test";
import "./unpivot.test";
import "./unstack.test";
import "./width.test";
import "./withColumns.test";
import "./withRowIndex.test";
import "./writeCsv.test";
import "./writeJson.test";

console.log("=========================================");
console.log("🎉 ALL DATAFRAME TESTS PASSED SUCCESSFULLY!");
console.log("=========================================");


