console.log("=========================================");
console.log("STARTING TEMPORAL EXPR MIXIN TESTS...");
console.log("=========================================");

import "./castTimeUnit.test";
import "./century.test";
import "./convertTimeZone.test";
import "./date.test";
import "./day.test";
import "./daysInMonth.test";
import "./epoch.test";
import "./hour.test";
import "./isBusinessDay.test";
import "./isLeapYear.test";
import "./isoYear.test";
import "./microsecond.test";
import "./millennium.test";
import "./millisecond.test";
import "./minute.test";
import "./month.test";
import "./monthEnd.test";
import "./monthStart.test";
import "./nanosecond.test";
import "./offsetDay.test";
import "./ordinalDay.test";
import "./quarter.test";
import "./replace.test";
import "./second.test";
import "./strftime.test";
import "./time.test";
import "./timestamp.test";
import "./totalDays.test";
import "./totalHours.test";
import "./totalMicroseconds.test";
import "./totalMilliseconds.test";
import "./totalMinutes.test";
import "./totalNanoseconds.test";
import "./totalSeconds.test";
import "./utcOffset.test";
import "./week.test";
import "./weekday.test";
import "./year.test";

console.log("✓ All TemporalExpr tests passed successfully!");
